### PR TITLE
update to v2

### PR DESCRIPTION
**Pull request by mko4444**
I've switched over the API to v2.

Only thing I am unsure about is on line 102, `body.sequence` — I don't remember this being in the v1 API response. @kn, can you explain a bit more about what was happening there?

Otherwise, should be good.

### CODE REVIEW

**Comment by kn** [comment]
thanks! v1 api used to have `body.sequence` which indicates sequential order of cast. for example, if I casted three casts: "hi", "I'm", and "kn", "hi" had body.sequence = 1, "kn" had body.sequence = 3. ncbot relied on this sequence number to determine if ncbot has recasted/checked new users cast for recast.

I run your change and got this error:
```
There are 31 new users created in the past 72 hours.
Could not fetch https://api.farcaster.xyz/v2/casts?fid=258&cursor=undefined: Unauthorized
file:///Users/kn/repos/kn/ncbot/index.js:91
    const { result, next } = casts
            ^

TypeError: Cannot destructure property 'result' of 'casts' as it is null.
    at getLatestSequenceRecastedPerAddress (file:///Users/kn/repos/kn/ncbot/index.js:91:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async recastNewUsers (file:///Users/kn/repos/kn/ncbot/index.js:143:5)
```

**Comment by vinliao** [comment]
Likely because the code is fetching without providing a Hub key. It should be done like this.

image

Edit: to generate your Hub key (with ncbot's seed phrase), use this: https://gist.github.com/danromero/87be7035aab27bf6a603b2c956022370. Then put the key on your `.env`, then attach `process.env.HUB_KEY` each time you fetch.

**Comment by mko4444** [comment]
@vinliao is right... I'm offline for a family thing but when I return will update. @kn will ping you but you'll have to pass in a custody token, which is generated using your custody wallet's seed phrase.

**Comment by vinliao** [comment]
I just made small a PR on your branch, @mkochakian: https://github.com/mkochakian/ncbot/pull/1.

**Comment by kn** [comment]
closing since collaborated on this PR https://github.com/kn/ncbot/pull/2

**Comment by kn** [comment]
@vinliao thanks for the help! happy to send a partial bounty if you can DM me your eth address on FC or Twitter (@kn) 🙏

**Pull request closed without merging**
